language: node_js
node_js:
  - "0.10.33"
services:
  - postgres
addons:
  postgresql: "9.3"
  sauce_connect: true
notifications:
  email: false
script:
  - npm run syntax
  - npm test
before_script:
  - psql -c 'create database runner_test;' -U postgres
  - cd test/scripts; ./create-db.sh runner_test; cd ../..;
  - PORT=9001 node server/index.js&
  - sleep 5
after_script:
  - npm run coveralls
  - npm run e2e
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/runner_test
    - AWS_BUCKET=bc-runner2-test
    # AWS_SECRET_ACCESS_KEY
    - secure: ZWz21c92C+ZGfrYs5JqYsSBUEcIZTsBb15yKHi3V2ynMK+d4rW40lftiO/kc+WXtwQ09EzDI3kAQX6G1bxCf42JHoVbOI9kZMDdokBleyPohJ+r0KkQBvejeBPxB1WrpTo5sBHSklR5rZ4yS7sC01BFMDJ8n+mtuTUJBDVWa5I0=
    # AWS_ACCESS_KEY_ID
    - secure: fuC+yRC2Ju0xkD6d9bXYoYmJ1InqdrXTHGTJq5/MGrp/fPpz5q+sGALbMtureStpwO2vGcRUJxCYDW8n2FHOGrEtQp+8pwJcJfImXDGnn/Ok/AJCYcJic813oNOd29e/Y2dvcCeH0k0Z/yVyIEDpT5KAeoifzxrD+Wnau91ZeDY=
    # SAUCE_USERNAME
    - secure: FQWpfic0W6TjgOhmFLdbKB9eOH78Q/g5hRIMm1FxrUUBe1+RZ7wTYM8nCbyLK/5/bp3sUJK5hBRKwTCsoVgQV4bup6dEKw/bU6x6RhBksTL1tuVBL4866xJqZBXP21JPzgnowzZhyluYIU+28PTwp2ASn6Fn3L4m7ERLVraqGB0=
    # SAUCE_ACCESS_KEY
    - secure: YC/ki/c8zaWacx21lE4uwEZ36sONFdOP3rrxy9pv5V5KGgRt/qLUN1ditTrpI6t+0U7B0Bs70jwbr2nsnFD4NiDkx3vgLUzymlGjHUf2tQAi8PnjvomXU9/+TozvYUE9RSf2EiCQzIjp0YhHJQEFyDV39Siv5X8nusnyLqmIYE4=
